version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: exogroup
      MYSQL_DATABASE: exogroup
      MYSQL_USER: exogroup
      MYSQL_PASSWORD: exogroup
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80